import Head from 'next/head'

function MyHead({
    title
} : {title : string}){
    return (
        <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    )
}

export default MyHead;